dataset: "MultispeakerVbee"

path:
  corpus_path: "corpus/MultispeakerVbee"
  # lexicon_path: "corpus/NgocHuyen/NgocHuyen/data_modeling_word/lexicon.txt"
  raw_path: "corpus/MultispeakerVbee"
  # wav_dir_path: "/home3/anhdtd/adaspeech/data/NgocHuyen/NEWS/wav_normalized_22k"
  preprocessed_path: "./preprocessed_data/MultispeakerVbee"

preprocessing:
  speaker_embedder: "DeepSpeaker" # support 'none', 'DeepSpeaker'
  speaker_embedder_cuda: True # since it's too large to load in a single GPU
  val_size: 512
  text:
    text_cleaners: ["basic_cleaners"]
    language: "vi"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
  duration:
    beta_binomial_scaling_factor: 1.0
